# Generated by Django 4.2.16 on 2024-09-30 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 9, 30, 14, 14, 16, 691963, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
